# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hardware.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'hardware.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ehardware.proto\" \n\x0bJointTarget\x12\x11\n\tpositions\x18\x01 \x03(\x01\"0\n\x08\x41rmState\x12\x11\n\tpositions\x18\x01 \x03(\x01\x12\x11\n\tis_moving\x18\x02 \x01(\x08\"\x07\n\x05\x45mpty\"/\n\x0bStatusReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2W\n\x0b\x41rmHardware\x12(\n\nMoveJoints\x12\x0c.JointTarget\x1a\x0c.StatusReply\x12\x1e\n\tGetStatus\x12\x06.Empty\x1a\t.ArmStateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hardware_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOINTTARGET']._serialized_start=18
  _globals['_JOINTTARGET']._serialized_end=50
  _globals['_ARMSTATE']._serialized_start=52
  _globals['_ARMSTATE']._serialized_end=100
  _globals['_EMPTY']._serialized_start=102
  _globals['_EMPTY']._serialized_end=109
  _globals['_STATUSREPLY']._serialized_start=111
  _globals['_STATUSREPLY']._serialized_end=158
  _globals['_ARMHARDWARE']._serialized_start=160
  _globals['_ARMHARDWARE']._serialized_end=247
# @@protoc_insertion_point(module_scope)
